### ISSUE TITLE
Using .set() function

### ISSUE THREAD

**Issue by unmanned15** [numat/mfc#3]
@patrickfuller 
.set(##.#) function is returning NoneType in python script? I can get it to work in command line but is there a way to use .set() within a python script? I am trying to set the flow controller to a particular setpoint but would like to do it in a script. 

Thanks for your help!

**Comment by patrickfuller** [comment]
Hi,

`set` works but it only supports asynchronous usage.

First, copy-paste the README tornado example to see if that works. Then, replace `get` with `set`. From [the source](https://github.com/numat/mfc/blob/master/mfc/__init__.py#L113-L120), `set` won't return anything but does allow a no-arg callback to fire on completion.

Hope this helps,
Pat

**Comment by unmanned15** [comment]
Thanks! Adding the callback parameter in the `set` worked!
